[package]
name = "storage-client"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets storage client"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
serde = "1.0.124"

bcs = "0.1.2"
dijets-crypto = { path = "../../crypto/crypto" }
dijets-logger = { path = "../../common/logger" }
dijets-infallible = { path = "../../common/infallible" }
dijets-secure-net = { path = "../../secure/net" }
dijets-types = { path = "../../types" }
dijets-workspace-hack = { path = "../../common/workspace-hack" }
storage-interface = { path = "../storage-interface" }

[features]
default = []
