[package]
name = "network-discovery"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets Network Peer Discovery"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
futures = "0.3.12"
once_cell = "1.7.2"
serde_yaml = "0.8.17"
tokio = { version = "1.8.1", features = ["full"] }

channel = {path = "../../common/channel"}
bcs = "0.1.2"
dijets-config = { path = "../../config"}
dijets-crypto = {path = "../../crypto/crypto"}
dijets-logger = {path = "../../common/logger"}
dijets-metrics = {path = "../../common/metrics"}
dijets-time-service = {path = "../../common/time-service"}
dijets-secure-storage = { path = "../../secure/storage" }
dijets-network-address-encryption = {path = "../../config/management/network-address-encryption"}
dijets-types = {path = "../../types"}
dijets-workspace-hack = { path = "../../common/workspace-hack" }
move-core-types = { path = "../../language/move-core/types" }
network = {path = "../../network"}
short-hex-str = { path = "../../common/short-hex-str" }
subscription-service = { path = "../../common/subscription-service" }

[dev-dependencies]
dijets-config = { path = "../../config", features = ["testing"]}
dijets-temppath = { path = "../../common/temppath" }
netcore = { path = "../netcore", features = ["fuzzing"] }
rand = "0.8.3"
