[package]
name = "cluster-test"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets cluster test"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
flate2 = { version = "1.0.20", features = ["rust_backend"], default-features = false }
hex = "0.4.3"
itertools = "0.10.0"
once_cell = "1.7.2"
rand = "0.8.3"
regex = { version = "1.4.3", default-features = false, features = ["std", "perf"] }
reqwest = { version = "0.11.2", features = ["blocking", "json"] }
serde_json = "1.0.64"
serde_yaml = "0.8.17"
termion = "1.5.6"
serde = { version = "1.0.124", features = ["derive"] }
structopt = "0.3.21"
rusoto_core = "0.46.0"
rusoto_autoscaling = "0.46.0"
rusoto_sts = "0.46.0"
rusoto_s3 = "0.46.0"
chrono = "0.4.19"
toml = { version = "0.5.8", default-features = false }

debug-interface = { path = "../../common/debug-interface"}
dijets-client = { path = "../../sdk/client"}
dijets-retrier = { path = "../../common/retrier" }
num_cpus = "1.13.0"

consensus-types = { path = "../../consensus/consensus-types" }
generate-key = { path = "../../config/generate-key" }
bcs = "0.1.2"
dijets-crypto = { path = "../../crypto/crypto" }
dijets-config = { path = "../../config" }
dijets-framework-releases = { path = "../../language/dijets-framework/releases" }
dijets-genesis-tool = { path = "../../config/management/genesis", features = ["testing"] }
dijets-global-constants = { path = "../../config/global-constants" }
dijets-logger = { path = "../../common/logger" }
dijets-management = { path = "../../config/management", features = ["testing"] }
dijets-mempool = { path = "../../mempool" }
dijets-infallible = { path = "../../common/infallible" }
dijets-network-address-encryption = { path = "../../config/management/network-address-encryption" }
dijets-node = { path = "../../dijets-node" }
dijets-operational-tool = {path = "../../config/management/operational", features = ["testing"] }
dijets-secure-storage = { path = "../../secure/storage", features = ["testing"] }
dijets-swarm = { path = "../dijets-swarm" }
dijets-temppath = { path = "../../common/temppath" }
dijets-time-service = { path = "../../common/time-service" }
dijets-types = { path = "../../types", features = ["fuzzing"] }
dijets-workspace-hack = { path = "../../common/workspace-hack" }
forge = { path = "../forge" }
language-e2e-tests = { path = "../../language/testing-infra/e2e-tests" }
move-core-types = { path = "../../language/move-core/types" }
network = { path = "../../network" }
network-builder = { path = "../../network/builder" }
seed-peer-generator = { path = "../../config/seed-peer-generator" }
state-sync = { path = "../../state-sync" }
dijets-sdk = { path = "../../sdk" }
dijets-transaction-builder = { path = "../../sdk/transaction-builder" }

futures = "0.3.12"
tokio = { version = "1.8.1", features = ["full"] }
async-trait = "0.1.42"

kube = "0.51.0"

k8s-openapi = { version = "0.11.0", default-features = false, features = ["v1_15"] }
