[package]
name = "serializer-tests"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets serializer tests"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dev-dependencies]
dijets-workspace-hack = { path = "../../../common/workspace-hack" }
proptest = "1.0.0"
proptest-derive = "0.3.0"
move-binary-format = { path = "../", features = ["fuzzing"] }

[features]
fuzzing = ["move-binary-format/fuzzing"]
