[package]
name = "dijets-swarm"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets swarm"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
ctrlc = { version = "3.1.8", default-features = false }
reqwest = { version = "0.11.2", features = ["blocking"], default-features = false }
structopt = "0.3.21"
thiserror = "1.0.24"
dijets-config = { path = "../../config", features = ["fuzzing"] }
dijets-framework-releases = { path = "../../language/dijets-framework/releases"}
debug-interface = { path = "../../common/debug-interface" }
dijets-logger = { path = "../../common/logger" }
dijets-genesis-tool = {path = "../../config/management/genesis", features = ["testing"] }
dijets-temppath = { path = "../../common/temppath" }
dijets-types = { path = "../../types" }
dijets-workspace-hack = { path = "../../common/workspace-hack" }
