apiVersion: v1
kind: Pod
metadata:
  name: {pod_name}
  labels:
    app: {pod_app}
    dijets-node: "true"
    peer_id: {pod_name}
  annotations:
    prometheus.io/should_be_scraped: "true"
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  serviceAccountName: clustertest
  nodeSelector:
    nodeType: validators
  nodeName: "{node_name}"
  containers:
  - name: fluent-bit
    image: 853397791086.dkr.ecr.us-west-2.amazonaws.com/fluent-bit:1.3.9
    imagePullPolicy: IfNotPresent
    command: ["/fluent-bit/bin/fluent-bit", "-c", "/opt/dijets/data/fluent-bit/fluent-bit.conf"]
    volumeMounts:
    - mountPath: /opt/dijets/data
      name: data
  - name: debug
    image: 853397791086.dkr.ecr.us-west-2.amazonaws.com/dijets/validator:{image_tag}
    imagePullPolicy: Always
    volumeMounts:
      - mountPath: /opt/dijets/data
        name: data
      - mountPath: /opt/dijets/etc
        name: config
    command:
      - "bash"
      - "-c"
      - |
        set -x;
        while true; do sleep 10; done
  - name: main
    image: 853397791086.dkr.ecr.us-west-2.amazonaws.com/dijets/validator:{image_tag}
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 7800m
    command: ["/opt/dijets/bin/dijets-node", "-f", "/opt/dijets/etc/node.yaml"]
    ports:
    - containerPort: 6180
    - containerPort: 6181
    - containerPort: 8000
    - containerPort: 9101
    - containerPort: 6191
    volumeMounts:
    - mountPath: /opt/dijets/data
      name: data
    - mountPath: /opt/dijets/etc
      name: config
    env:
    - name: RUST_LOG
      value: "debug"
    - name: STRUCT_LOG_TCP_ADDR
      value: "127.0.0.1:5044"
    - name: RUST_BACKTRACE
      value: "1"
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  volumes:
  - name: data
    hostPath:
      path: /data
      type: Directory
  - name: config
    hostPath:
      path: /config
      type: Directory
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: dijets-node
            operator: Exists
        topologyKey: "kubernetes.io/hostname"
  terminationGracePeriodSeconds: 5
  tolerations:
  - key: "validators"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node.kubernetes.io/not-ready"
    operator: "Exists"
    effect: "NoSchedule"
