[package]
name = "dijets-vm"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets VM runtime"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
fail = "0.4.0"
once_cell = "1.7.2"
rayon = "1.5.0"
mirai-annotations = "1.10.1"
tracing = "0.1.16"

bcs = "0.1.2"
dijets-crypto = { path = "../../crypto/crypto" }
dijets-logger = { path = "../../common/logger" }
dijets-metrics = { path = "../../common/metrics" }
dijets-state-view = { path = "../../storage/state-view" }
dijets-types = { path = "../../types" }
dijets-workspace-hack = { path = "../../common/workspace-hack" }
move-core-types = { path = "../move-core/types" }
move-vm-runtime = { path = "../move-vm/runtime" }
move-vm-types = { path = "../move-vm/types" }
move-binary-format = { path = "../move-binary-format" }
move-stdlib = { path = "../move-stdlib" }
dijets-framework = { path = "../dijets-framework" }
serde_json = "1.0.64"
serde = { version = "1.0.124", default-features = false }


[dev-dependencies]
proptest = "1.0.0"

dijets-types = { path = "../../types", features = ["fuzzing"] }
dijets-framework-releases = { path = "../dijets-framework/releases" }

[features]
default = []
mirai-contracts = []
fuzzing = ["move-binary-format/fuzzing","move-vm-types/fuzzing"]
failpoints = ["fail/failpoints", "move-vm-runtime/failpoints"]
