[package]
name = "jsonrpc-integration-tests"
version = "0.0.0"
authors = ["Dijets Association <opensource@dijets.com>"]
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
bcs = "0.1.2"
hex = "0.4.3"
reqwest = { version = "0.11.2", features = ["blocking", "json"], default_features = false }
serde_json = "1.0.64"

dijets-json-rpc-types = { path = "../types" }
dijets-sdk = { path = "../../sdk" }
forge = { path = "../../testsuite/forge" }
dijets-workspace-hack = { path = "../../common/workspace-hack" }

[[test]]
name = "jsonrpc-forge"
harness = false
