[package]
name = "invalid-mutations"
version = "0.1.0"
edition = "2018"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets invalid mutations"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false

[dependencies]
move-core-types = { path = "../../move-core/types" }
move-binary-format = { path = "../../move-binary-format" }
proptest = "1.0.0"
dijets-workspace-hack = { path = "../../../common/workspace-hack" }

[features]
default = []
