[package]
name = "functional-tests"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets functional tests"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
move-command-line-common = { path = "../../move-command-line-common" }
hex = "0.4.3"
dijets-state-view = { path = "../../../storage/state-view" }
dijets-types = { path = "../../../types" }
dijets-vm = { path = "../../dijets-vm" }
move-binary-format = { path = "../../move-binary-format" }
bytecode-verifier = { path = "../../bytecode-verifier" }
language-e2e-tests = { path = "../e2e-tests" }
dijets-keygen = { path = "../../dijets-tools/dijets-keygen" }
dijets-config = { path = "../../../config", features = ["fuzzing"] }
dijets-crypto = { path = "../../../crypto/crypto" }
dijets-workspace-hack = { path = "../../../common/workspace-hack" }
once_cell = "1.7.2"
regex = { version = "1.4.3", default-features = false, features = ["std", "perf"] }
thiserror = "1.0.24"
aho-corasick = "0.7.14"
termcolor = "1.1.2"
datatest-stable = "0.1.1"
mirai-annotations = "1.10.1"
move-core-types = { path = "../../move-core/types" }
dijets-framework = { path = "../../dijets-framework" }
dijets-framework-releases = { path = "../../dijets-framework/releases" }
itertools = "0.10.0"
difference = "2.0.0"
term_size = "0.3.2"
vm-genesis = { path = "../../tools/vm-genesis" }
