[package]
name = "seed-peer-generator"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets seed peer generator"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
hex = "0.4.3"
rand = "0.8.3"
serde_yaml = "0.8.17"
structopt = "0.3.21"
thiserror = "1.0.24"

bcs = "0.1.2"
dijets-config = { path = ".." }
dijets-crypto = { path = "../../crypto/crypto" }
dijets-client = { path = "../../sdk/client", features = ["blocking"], default-features = false }
dijets-logger = { path = "../../common/logger" }
dijets-temppath = { path = "../../common/temppath" }
dijets-types = { path = "../../types" }
dijets-workspace-hack = { path = "../../common/workspace-hack" }

[dev-dependencies]
dijets-types = {path = "../../types", features = ["fuzzing"]}

[features]
default = []
