[package]
name = "dijets-fuzz"
version = "0.1.0"
edition = "2018"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets fuzzer fuzz"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "=0.3.2"
dijets-fuzzer = { path = ".." }
dijets-workspace-hack = { path = "../../../common/workspace-hack" }
once_cell = "1.7.2"

# Prevent this from interfering with workspaces

[[bin]]
name = "fuzz_runner"
path = "fuzz_targets/fuzz_runner.rs"
test = false

# used for integration with Google OSS-Fuzz (see README)
[[bin]]
name = "fuzzer_builder"
path = "google-oss-fuzz/fuzzer_builder.rs"
test = false
