[package]
name = "ir-testsuite"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets functional tests"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dev-dependencies]
anyhow = "1.0.38"
bytecode-verifier = { path = "../bytecode-verifier" }
datatest-stable = "0.1.1"
functional-tests = { path = "../testing-infra/functional-tests" }
ir-to-bytecode = { path = "../compiler/ir-to-bytecode" }
dijets-types = { path = "../../types" }
dijets-workspace-hack = { path = "../../common/workspace-hack" }
move-ir-types = { path = "../move-ir/types" }
dijets-framework-releases = { path = "../dijets-framework/releases" }
move-binary-format = { path = "../move-binary-format" }
move-core-types = { path = "../move-core/types" }
move-symbol-pool = { path = "../move-symbol-pool" }


[[test]]
name = "testsuite"
harness = false
