[package]
name = "cli"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets client"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
chrono = "0.4.19"
hex = "0.4.3"
proptest = { version = "1.0.0", optional = true }
rustyline = "8.0.0"
rust_decimal = "1.10.3"
num-traits = "0.2.14"
once_cell = "1.7.2"
reqwest = { version = "0.11.2", features = ["blocking", "json"] }
serde = { version = "1.0.124", features = ["derive"] }
structopt = "0.3.21"
tokio = { version = "1.8.1", features = ["full"] }
walkdir = "2.3.1"

dijets-config = { path = "../../config" }
generate-key = { path = "../../config/generate-key" }
crash-handler = { path = "../../common/crash-handler" }
dijets-crypto = { path = "../../crypto/crypto" }
bcs = "0.1.2"
dijets-wallet = { path = "dijets-wallet" }
dijets-client = { path = "../../sdk/client" }
dijets-infallible = { path = "../../common/infallible" }
dijets-logger =  { path = "../../common/logger" }
dijets-metrics = { path = "../../common/metrics" }
dijets-types = { path = "../../types" }
dijets-temppath = { path = "../../common/temppath/" }
dijets-workspace-hack = { path = "../../common/workspace-hack" }
dijets-resource-viewer = { path = "../../language/tools/dijets-resource-viewer" }
dijets-framework = { path = "../../language/dijets-framework" }
dijets-framework-releases = { path = "../../language/dijets-framework/releases" }
dijets-transaction-builder = { path = "../../sdk/transaction-builder" }
move-symbol-pool = { path = "../../language/move-symbol-pool" }
move-vm-test-utils = { path = "../../language/move-vm/test-utils" }
compiler = { path = "../../language/compiler" }

[dev-dependencies]
proptest = "1.0.0"

dijets-types = { path = "../../types", features = ["fuzzing"] }

[features]
default = []
fuzzing = ["proptest", "dijets-crypto/fuzzing", "dijets-types/fuzzing"]
