[package]
name = "storage-interface"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets storage interface"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
itertools = "0.10.0"
serde = { version = "1.0.124", default-features = false }
thiserror = "1.0.24"
parking_lot = "0.11.1"

bcs = "0.1.2"
dijets-crypto = { path = "../../crypto/crypto" }
dijets-secure-net = { path = "../../secure/net" }
dijets-state-view = { path = "../state-view" }
dijets-types = { path = "../../types" }
dijets-workspace-hack = { path = "../../common/workspace-hack" }
scratchpad = { path = "../scratchpad" }
move-core-types = { path = "../../language/move-core/types" }

[features]
default = []
fuzzing = ["dijets-types/fuzzing"]
