[package]
name = "dijets-json-rpc-types"
version = "0.0.2"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets JSONRPC Types"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = ["crates-io"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
hex = "0.4.3"
serde = { version = "1.0.124", default-features = false }
serde_json = "1.0.64"

bcs = "0.1.2"
dijets-crypto = { path = "../../crypto/crypto", version = "0.0.2"  }
dijets-transaction-builder = { path = "../../sdk/transaction-builder", version = "0.0.2" }
dijets-types = { path = "../../types", version = "0.0.2" }
move-core-types = { path = "../../language/move-core/types", version = "0.0.2"  }
num-derive = "0.3.3"
num-traits = "0.2.14"
thiserror = "1.0.24"

[dev-dependencies]
dijets-workspace-hack = { path = "../../common/workspace-hack" }
