[package]
name = "dijets-writeset-generator"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Generating writesets used for incident management"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
structopt = "0.3.21"
tempfile = "3.2.0"
handlebars = "3.5.3"
serde = { version = "1.0.124", default-features = false }
serde_json = "1.0.64"
once_cell = "1.7.2"

bytecode-verifier = { path = "../../bytecode-verifier" }
dijets-workspace-hack = { path = "../../../common/workspace-hack" }
dijets-crypto-derive = { path = "../../../crypto/crypto-derive" }
dijets-crypto = { path = "../../../crypto/crypto" }
dijets-types = { path = "../../../types" }
dijets-framework-releases = { path = "../../dijets-framework/releases" }
dijets-framework = { path = "../../dijets-framework" }
move-lang = { path = "../../move-lang" }
bcs = "0.1.2"
dijets-state-view = { path = "../../../storage/state-view" }
dijets-validator-interface = { path = "../dijets-validator-interface" }
dijets-transaction-replay = { path = "../transaction-replay" }
dijetsdb = { path = "../../../storage/dijetsdb" }
dijets-vm = { path = "../../dijets-vm" }
move-binary-format = { path = "../../move-binary-format"}
move-vm-types = { path = "../../move-vm/types" }
move-core-types = { path = "../../move-core/types" }
move-vm-runtime = { path = "../../move-vm/runtime" }
move-vm-test-utils = { path = "../../move-vm/test-utils" }
