[package]
name = "ir-to-bytecode-syntax"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets ir to bytecode syntax"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
hex = "0.4.3"
move-ir-types = { path = "../../../move-ir/types" }
move-core-types = { path = "../../../move-core/types" }
move-symbol-pool = { path = "../../../move-symbol-pool" }
dijets-workspace-hack = { path = "../../../../common/workspace-hack" }

[features]
default = []
