[package]
name = "errmapgen"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
publish = false
edition = "2018"
license = "Apache-2.0"

[dependencies]
# dijets dependencies
move-command-line-common = { path = "../../move-command-line-common" }
move-model = { path = "../../move-model" }
dijets-workspace-hack = { path = "../../../common/workspace-hack" }
move-core-types = { path = "../../move-core/types" }
bcs = "0.1.2"

# external dependencies
log = "0.4.14"
anyhow = "1.0.38"
serde = { version = "1.0.124", features = ["derive"] }

[dev-dependencies]
codespan-reporting = "0.11.1"
move-prover = { path = ".." }
datatest-stable = "0.1.1"
