[package]
name = "dijets-github-client"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
repository = "https://github.com/dijets/dijets"
description = "Dijets's Restful GitHub Client"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
serde = { version = "1.0.124", features = ["derive"], default-features = false }
serde_json = "1.0.64"
thiserror = "1.0.24"
ureq = { version = "1.5.4", features = ["json", "native-tls"], default-features = false }

dijets-workspace-hack = { path = "../../../common/workspace-hack" }
proxy = { path = "../../../common/proxy" }

[dev-dependencies]
base64 = "0.13.0"
