[package]
name = "sdk-compatibility"
version = "0.0.0"
authors = ["Dijets Association <opensource@dijets.com>"]
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1"
bcs = "0.1.2"
rand = "0.8.3"
dijets-sdk = { path = ".." }
once_cell = "1.7.2"

dijets-workspace-hack = { path = "../../common/workspace-hack" }
