[package]
name = "netcore"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets netcore"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bytes = "1.0.1"
futures = "0.3.12"
pin-project = "1.0.5"
serde = { version = "1.0.124", default-features = false }
tokio = { version = "1.8.1", features = ["full"] }
tokio-util = { version = "0.6.4", features = ["compat"] }
url = { version = "2.2.1" }

dijets-workspace-hack = { path = "../../common/workspace-hack" }
dijets-types = { path = "../../types" }
memsocket = { path = "../memsocket", optional = true }
proxy = { path = "../../common/proxy" }

[dev-dependencies]
dijets-logger = { path = "../../common/logger" }
memsocket = { path = "../memsocket" }

[features]
default = []
fuzzing = ["memsocket/fuzzing", "dijets-types/fuzzing"]
testing = ["memsocket/testing"]
