[package]
name = "memsocket"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets memsocket"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
edition = "2018"
publish = false

[dependencies]
futures = "0.3.12"
bytes = "1.0.1"
once_cell = "1.7.2"
dijets-infallible = { path = "../../common/infallible" }
dijets-workspace-hack = { path = "../../common/workspace-hack" }

[features]
default = []
fuzzing = []
testing = []
