[package]
name = "move-command-line-common"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Move shared command line and file tools"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
difference = "2.0.0"
walkdir = "2.3.1"

dijets-workspace-hack = { path = "../../common/workspace-hack" }
