[package]
name = "storage-service"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets storage service"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
tokio = { version = "1.8.1", features = ["full"] }
futures = "0.3.12"

bcs = "0.1.2"
dijets-config = { path = "../../config" }
dijets-crypto = { path = "../../crypto/crypto" }
dijetsdb = { path = "../dijetsdb" }
dijets-logger = { path = "../../common/logger" }
dijets-metrics = { path = "../../common/metrics" }
dijets-secure-net = { path = "../../secure/net" }
storage-interface = { path = "../storage-interface" }
dijets-types = { path = "../../types" }
dijets-workspace-hack = { path = "../../common/workspace-hack" }
rand = { version = "0.8.3", optional = true }
storage-client = { path = "../storage-client", optional = true }
proptest = { version = "1.0.0", optional = true }

[dev-dependencies]
itertools = "0.10.0"
dijetsdb = { path = "../dijetsdb", features = ["fuzzing"] }
dijets-temppath = { path = "../../common/temppath" }
proptest = "1.0.0"
storage-client = { path = "../storage-client" }

[features]
default = []
fuzzing = ["proptest", "dijetsdb/fuzzing", "rand"]
