[package]
name = "dijetssum"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets dijetsdb data access tool for data analysis or human read"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
structopt = "0.3.21"
serde = "1.0.124"
serde_json = "1.0.64"

dijetsdb = { path = "../dijetsdb", features = ["dijetssum"] }
dijets-crypto = { path = "../../crypto/crypto" }
dijets-types = { path = "../../types" }
dijets-workspace-hack = { path = "../../common/workspace-hack" }
storage-interface = { path = "../storage-interface" }
