[package]
name = "dijets-crypto-derive"
version = "0.0.2"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets custom derives for `dijets-crypto`"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = ["crates-io"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.64", features = ["derive"] }
quote = "1.0.9"
proc-macro2 = "1.0.24"

[dev-dependencies]
anyhow = "1.0.38"
dijets-workspace-hack = { path = "../../common/workspace-hack" }
