[package]
name = "dijetsdb"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets dijetsdb"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
arc-swap = "1.2.0"
byteorder = "1.4.3"
itertools = "0.10.0"
once_cell = "1.7.2"
num-derive = "0.3.3"
num-traits = "0.2.14"
proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", optional = true }
serde = "1.0.124"
thiserror = "1.0.24"

accumulator = { path = "../accumulator" }
bcs = "0.1.2"
dijets-config = { path = "../../config" }
dijets-crypto = { path = "../../crypto/crypto" }
dijets-jellyfish-merkle = { path = "../jellyfish-merkle" }
dijets-logger = { path = "../../common/logger" }
dijets-metrics = { path = "../../common/metrics" }
dijets-infallible = { path = "../../common/infallible" }
dijets-proptest-helpers = { path = "../../common/proptest-helpers", optional = true }
dijets-temppath = { path = "../../common/temppath", optional = true }
dijets-types = { path = "../../types" }
dijets-workspace-hack = { path = "../../common/workspace-hack" }
move-core-types = {path = "../../language/move-core/types"}

num-variants = { path = "../../common/num-variants" }
schemadb = { path = "../schemadb" }
storage-interface = { path = "../storage-interface" }

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
rand = "0.8.3"

dijets-jellyfish-merkle = { path = "../jellyfish-merkle", features = ["fuzzing"] }
dijets-proptest-helpers = { path = "../../common/proptest-helpers" }
dijets-temppath = { path = "../../common/temppath" }
dijets-types = { path = "../../types", features = ["fuzzing"] }

[features]
default = []
dijetssum = []
fuzzing = ["proptest", "proptest-derive", "dijets-proptest-helpers", "dijets-temppath", "dijets-crypto/fuzzing", "dijets-jellyfish-merkle/fuzzing", "dijets-types/fuzzing"]
