[package]
name = "consensus-types"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
itertools = "0.10.0"
mirai-annotations = { version = "1.10.1", default-features = false }
proptest = { version = "1.0.0", optional = true }
serde = { version = "1.0.124", default-features = false }

executor-types = { path = "../../execution/executor-types" }
bcs = "0.1.2"
dijets-crypto = { path = "../../crypto/crypto" }
dijets-crypto-derive = { path = "../../crypto/crypto-derive" }
dijets-infallible = { path = "../../common/infallible" }
dijets-types = { path = "../../types" }
dijets-workspace-hack = { path = "../../common/workspace-hack" }
short-hex-str = { path = "../../common/short-hex-str" }


[dev-dependencies]
proptest = "1.0.0"
serde_json = "1.0.64"

dijets-types = { path = "../../types", features = ["fuzzing"] }

[features]
default = []
fuzzing = ["proptest", "dijets-types/fuzzing", "dijets-crypto/fuzzing"]
