[package]
name = "move-symbol-pool"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "A static, global string table for Move tools"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
once_cell = "1.7.2"
serde = { version = "1.0.124", features = ["derive"] }

dijets-workspace-hack = { path = "../../common/workspace-hack" }

[dev-dependencies]
serde_json = { version = "1.0.64" }

[features]
default = []
