[package]
name = "dijets-transaction-builder"
version = "0.0.2"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Generated transaction builders"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = ["crates-io"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
bcs = "0.1.2"
once_cell = "1.7.2"
serde = { version = "1.0.124", features = ["derive"] }

move-core-types = { path = "../../language/move-core/types", version = "0.0.2" }
dijets-types = { path = "../../types", version = "0.0.2" }

proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", optional = true }

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
move-core-types = { path = "../../language/move-core/types", features = ["fuzzing"] }
dijets-workspace-hack = { path = "../../common/workspace-hack" }

[features]
default = []
fuzzing = ["proptest", "proptest-derive", "move-core-types/fuzzing"]
