[package]
name = "dijets-wallet"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets wallet"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
rand = "0.8.3"
hex = "0.4.3"
hmac = "0.10.1"
byteorder = "1.4.3"
pbkdf2 = "0.7.3"
serde = "1.0.124"
sha2 = "0.9.3"
thiserror = "1.0.24"
ed25519-dalek = { version = "0.1.0", package = "ed25519-dalek-fiat", default-features = false, features = ["std", "fiat_u64_backend"] }
dijets-crypto = { path = "../../../crypto/crypto", features = ["fuzzing"] }
dijets-temppath = { path = "../../../common/temppath/" }
dijets-types = { path = "../../../types" }
dijets-workspace-hack = { path = "../../../common/workspace-hack" }
mirai-annotations = "1.10.1"

[features]
default = []
fuzzing = ["dijets-types/fuzzing"]
