[package]
name = "bytecode-verifier-tests"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets bytecode verifier tests"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dev-dependencies]
petgraph = "0.5.1"
proptest = "1.0.0"

bytecode-verifier = { path = "../" }
dijets-workspace-hack = { path = "../../../common/workspace-hack" }
invalid-mutations = { path = "../invalid-mutations" }
move-core-types = { path = "../../move-core/types" }
move-binary-format = { path = "../../move-binary-format", features = ["fuzzing"] }

[features]
fuzzing = ["move-binary-format/fuzzing"]
