[package]
name = "dijets-storage-inspector"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
structopt = "0.3.21"
tempfile = "3.2.0"

dijets-framework-releases = { path = "../../language/dijets-framework/releases" }
dijetsdb = { path = "../dijetsdb" }
dijets-config = { path = "../../config" }
dijets-crypto = { path = "../../crypto/crypto" }
dijets-types = { path = "../../types" }
dijets-logger = { path = "../../common/logger" }
dijets-workspace-hack = { path = "../../common/workspace-hack" }
storage-interface = { path = "../storage-interface" }
