[package]
name = "executor-benchmark"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets executor benchmark"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
itertools = { version = "0.10.0", default-features = false }
rand = "0.8.3"
rayon = "1.5.0"
structopt = "0.3.21"
criterion = "0.3.4"

executor = { path = "../executor" }
executor-types = { path = "../executor-types" }
dijetsdb = { path = "../../storage/dijetsdb" }
dijets-config = { path = "../../config" }
dijets-crypto = { path = "../../crypto/crypto" }
dijets-genesis-tool = {path = "../../config/management/genesis", features = ["testing"] }
dijets-infallible = { path = "../../common/infallible" }
dijets-logger = { path = "../../common/logger" }
dijets-types = { path = "../../types" }
dijets-vm= { path = "../../language/dijets-vm" }
dijets-workspace-hack = { path = "../../common/workspace-hack" }
storage-client = { path = "../../storage/storage-client" }
storage-interface = { path = "../../storage/storage-interface" }
storage-service = { path = "../../storage/storage-service" }
dijets-transaction-builder = { path = "../../sdk/transaction-builder" }

[features]
default = []
fuzzing = ["dijets-config/fuzzing", "dijets-crypto/fuzzing", "dijets-types/fuzzing"]

[[bench]]
name = "executor_benchmark"
harness = false
