[package]
name = "executor-test-helpers"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets executor test helpers"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
rand = "0.8.3"
tempfile = "3.2.0"

executor = { path = "../executor" }
executor-types = { path = "../executor-types" }
dijetsdb = { path = "../../storage/dijetsdb", features = ["fuzzing"] }
dijets-config = { path = "../../config" }
dijets-crypto = { path = "../../crypto/crypto" }
dijets-genesis-tool = {path = "../../config/management/genesis", features = ["testing"] }
dijets-temppath = { path = "../../common/temppath" }
dijets-types = { path = "../../types", features = ["fuzzing"] }
dijets-vm = { path = "../../language/dijets-vm" }
dijets-workspace-hack = { path = "../../common/workspace-hack" }
storage-interface = { path = "../../storage/storage-interface" }
storage-service = { path = "../../storage/storage-service" }
dijets-transaction-builder = { path = "../../sdk/transaction-builder" }
vm-genesis = { path = "../../language/tools/vm-genesis" }
