[package]
name = "dijets-state-view"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets state view"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
dijets-crypto = { path = "../../crypto/crypto" }
dijets-types = { path = "../../types" }
dijets-workspace-hack = { path = "../../common/workspace-hack" }

[features]
default = []
fuzzing = ["dijets-types/fuzzing"]
