[package]
name = "dijets-framework"
version = "0.1.0"
edition = "2018"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets stdlib"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false

[dependencies]
bytecode-verifier = { path = "../bytecode-verifier" }
abigen = { path = "../move-prover/abigen" }
docgen = { path = "../move-prover/docgen" }
move-command-line-common = { path = "../move-command-line-common" }
errmapgen = { path = "../move-prover/errmapgen" }
move-lang = { path = "../move-lang" }
move-prover = { path = "../move-prover" }
dijets-crypto = { path = "../../crypto/crypto" }
dijets-types = { path = "../../types" }
dijets-workspace-hack = { path = "../../common/workspace-hack" }
move-binary-format = { path = "../move-binary-format" }
transaction-builder-generator = { path = "../transaction-builder/generator" }
move-stdlib = { path = "../move-stdlib" }
move-symbol-pool = { path = "../move-symbol-pool" }
move-core-types = { path = "../move-core/types" }
move-vm-types = { path = "../move-vm/types" }
move-vm-runtime = { path = "../move-vm/runtime" }

bcs = "0.1.2"
anyhow = "1.0.38"
clap = "2.33.3"
log = "0.4.14"
rayon = "1.5.0"
sha2 = "0.9.3"
walkdir = "2.3.1"
once_cell = "1.7.2"
smallvec = "1.6.1"

[dev-dependencies]
datatest-stable = "0.1.1"
move-unit-test = { path = "../tools/move-unit-test" }
dijets-vm = { path = "../dijets-vm" }

tempfile = "3.2.0"
dir-diff = "0.3.2"

[features]
default = []
fuzzing = ["dijets-types/fuzzing"]
