# This compose file defines a single validator node test network,
# along with a faucet that connects to it over json-rpc.
# In addition, it offers the following facilities:
# * JSON-RPC endpoint at http://127.0.0.1:8080.
# * chain_id of 4 / TESTING
# * The faucet can be accessed at 127.0.0.1:8000

# Additional information:
# * If you use this compose for different Dijets Networks, you will need remove the db volume first.
# * If you would like to use the current Dijets version within this repository, execute the
#     `build.sh` in `docker/validator` and change the image tag below to dijets_e2e:latest
# * Validator images can be found at https://hub.docker.com/r/devnet/validator/tags
# * Faucet images can be found at https://hub.docker.com/r/devnet/faucet/tags

# Monitoring:
# If you want to install the monitoring components for your validator-testnet
# you can symlink the ../monitoring folder into this directory.
# Note that you will need to rename the monitoring docker-compose.yaml file to avoid duplication.
# e.g. rename it to docker-compose.mon.yaml
# You will also need to configure the network in the monitoring compose file,
# so that the container can join the same network and talk to each other.
# To start both validator and monitoring, run `docker-compose -f docker-compose.yaml -f docker-compose.mon.yaml up -d`

version: "3.8"
services:
  validator:
    # Note this image currently does not support this, will update to the appropriate minimum
    # version shortly
    image: "dijets/validator:${IMAGE_TAG:-devnet}"
    networks:
      shared:
    volumes:
      - type: volume
        source: dijets-shared
        target: /opt/dijets/var
      - type: bind
        source: ./validator_node_template.yaml
        target: /opt/dijets/var/validator_node_template.yaml
    command: ["/opt/dijets/bin/dijets-node", "--test", "--config", "/opt/dijets/var"]
    ports:
      - "8080:8080"
    expose:
      - 9101

  faucet:
    image: "dijets/faucet:${IMAGE_TAG:-devnet}"
    depends_on:
      - validator
    networks:
      shared:
    volumes:
      - type: volume
        source: dijets-shared
        target: /opt/dijets/var
    command: >
      /bin/bash -c "
        for i in {1..10}
        do
          if [[ -s /opt/dijets/var/mint.key ]]
          then
            /opt/dijets/bin/dijets-faucet \
              --address 0.0.0.0 \
              --port 8000 \
              --chain-id TESTING \
              --mint-key-file-path /opt/dijets/var/mint.key \
              --server-url http://validator:8080/v1
            exit $$?
          else
            echo 'Validator has not populated mint.key yet. Is it running?'
            sleep 1
          fi
        done
        exit 1
      "
    ports:
      - "8000:8000"

networks:
  shared:
    name: "dijets-docker-compose-shared"
    ipam:
      config:
        - subnet: 172.16.1.0/24

volumes:
  dijets-shared:
    name: dijets-shared
