[package]
name = "bytecode-interpreter"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
publish = false
edition = "2018"
license = "Apache-2.0"

[dependencies]
# dijets dependencies
bytecode = { path = "../bytecode" }
bytecode-interpreter-crypto = { path = "crypto" }
dijets-workspace-hack = { path = "../../../common/workspace-hack" }
move-binary-format = { path = "../../move-binary-format" }
move-core-types = { path = "../../move-core/types" }
move-model = { path = "../../move-model" }
move-vm-runtime = { path = "../../move-vm/runtime" }

# external dependencies
anyhow = "1.0.38"
codespan-reporting = "0.11.1"
itertools = "0.10.0"
num = "0.4.0"
serde = { version = "1.0.124", features = ["derive"] }
structopt = "0.3.21"

[dev-dependencies]
datatest-stable = "0.1.1"
move-prover-test-utils = { path = "../test-utils" }
