[package]
name = "bytecode-interpreter-testsuite"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
publish = false
edition = "2018"
license = "Apache-2.0"

[dev-dependencies]
dijets-workspace-hack = { path = "../../../common/workspace-hack" }

# dijets dependencies
bytecode-interpreter = { path = "../interpreter" }
move-command-line-common = { path = "../../move-command-line-common" }
move-prover-test-utils = { path = "../test-utils" }
move-stdlib = { path = "../../move-stdlib" }
move-unit-test = { path = "../../tools/move-unit-test" }

# external dependencies
anyhow = "1.0.38"
datatest-stable = "0.1.1"

[[test]]
name = "concrete_check_testsuite"
harness = false
