[package]
name = "read-write-set-types"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Type definition for read/write set inference for Move bytecode programs"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
dijets-workspace-hack = { path = "../../../../common/workspace-hack" }
move-binary-format = { path = "../../../move-binary-format" }
move-core-types = { path = "../../../move-core/types" }
