[package]
name = "smoke-test"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets smoke test"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bcs = "0.1.2"
proptest = "1.0.0"
tokio = { version = "1.8.1", features = ["full"] }

dijets-events-fetcher = { path = "../../language/dijets-tools/dijets-events-fetcher" }
dijets-sdk = { path = "../../sdk" }
forge = { path = "../forge" }

[dev-dependencies]
anyhow = "1.0.38"
base64 = "0.13.0"
hex = "0.4.3"
once_cell = "1.7.2"
num = "0.4.0"
num-traits = "0.2.14"
rand = "0.8.3"
regex = "1.4.3"
rust_decimal = "1.10.3"
rusty-fork = "0.3.0"
serde_yaml = "0.8.17"

backup-cli = { path = "../../storage/backup/backup-cli" }
cli = { path = "../cli", features = ["fuzzing"]  }
dijets-framework-releases = { path = "../../language/dijets-framework/releases" }
debug-interface = { path = "../../common/debug-interface" }
futures = "0.3.12"
generate-key = { path = "../../config/generate-key" }
move-move-command-line-common = { path = "../../language/move-command-line-common", package = "move-command-line-common" }
move-stdlib = { path = "../../language/move-stdlib" }
dijets-config = { path = "../../config" }
dijets-crypto = { path = "../../crypto/crypto" }
dijets-genesis-tool = {path = "../../config/management/genesis", features = ["testing"] }
dijets-global-constants = { path = "../../config/global-constants" }
dijets-infallible = { path = "../../common/infallible" }
dijets-json-rpc = { path = "../../json-rpc" }
dijets-json-rpc-types = { path = "../../json-rpc/types" }
dijets-key-manager = { path = "../../secure/key-manager" }
dijets-logger = { path = "../../common/logger" }
dijets-management = { path = "../../config/management", features = ["testing"] }
dijets-operational-tool = {path = "../../config/management/operational", features = ["testing"] }
dijets-secure-storage = { path = "../../secure/storage", features = ["testing"] }
dijets-smoke-test-attribute = { path = "../smoke-test/attribute" }
dijets-swarm = { path = "../dijets-swarm"}
dijets-temppath = { path = "../../common/temppath" }
dijets-time-service = { path = "../../common/time-service", features = ["testing"] }
dijets-transaction-replay = { path = "../../language/dijets-tools/transaction-replay" }
dijets-types = { path = "../../types" }
dijets-vault-client = { path = "../../secure/storage/vault", features = ["fuzzing"] }
dijets-validator-interface = { path = "../../language/dijets-tools/dijets-validator-interface" }
dijets-workspace-hack = { path = "../../common/workspace-hack" }
dijets-writeset-generator = { path = "../../language/dijets-tools/writeset-transaction-generator" }
dijets-framework = { path = "../../language/dijets-framework" }
dijets-transaction-builder = { path = "../../sdk/transaction-builder" }

[[test]]
name = "forge"
harness = false
