[package]
name = "forge-cli"
version = "0.0.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Forged in Fire"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
dijets-sdk = { path = "../../sdk" }
forge = { path = "../forge" }
itertools = "0.10.0"
rand_core = "0.6.2"
structopt = "0.3.21"
tokio = { version = "1.8.1", features = ["full"] }
compatibility-test = { path = "../compatibility-test" }

dijets-workspace-hack = { path = "../../common/workspace-hack" }

[[bin]]
name = "forge"
path = "src/main.rs"
