[package]
name = "move-vm-test-utils"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Move VM Test Utils"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"

dijets-workspace-hack = { path = "../../../common/workspace-hack" }
move-vm-runtime = { path = "../runtime" }
move-core-types = {path = "../../move-core/types" }
move-binary-format = { path = "../../move-binary-format" }
