[package]
name = "dijets-secure-storage"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
repository = "https://github.com/dijets/dijets"
description = "Dijets's Persistent, Secure Storage"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
base64 = "0.13.0"
chrono = "0.4.19"
enum_dispatch = "0.3.5"
rand = "0.8.3"
serde = { version = "1.0.124", features = ["rc"], default-features = false }
serde_json = "1.0.64"
thiserror = "1.0.24"

bcs = "0.1.2"
dijets-crypto = { path = "../../crypto/crypto" }
dijets-github-client = { path = "github" }
dijets-infallible = { path = "../../common/infallible" }
dijets-logger = { path = "../../common/logger" }
dijets-temppath = { path = "../../common/temppath" }
dijets-time-service = { path = "../../common/time-service" }
dijets-vault-client = { path = "vault" }
dijets-workspace-hack = { path = "../../common/workspace-hack" }

[dev-dependencies]
dijets-crypto = { path = "../../crypto/crypto", features = ["fuzzing"] }
dijets-crypto-derive = { path = "../../crypto/crypto-derive" }
rand = "0.8.3"

[features]
fuzzing = ["dijets-crypto/fuzzing"]
testing = []
