[package]
name = "forge"
version = "0.0.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Forged in Fire"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
futures = "0.3.12"
itertools = "0.10.0"
rand = "0.8.3"
rayon = "1.5.0"
regex = "1.4.3"
structopt = "0.3.21"
termcolor = "1.1.2"
tokio = { version = "1.8.1", features = ["full"] }
reqwest = { version = "0.11.2", features = ["blocking", "json"] }
rand_core = "0.6.2"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
url = "2.2.2"
tempfile = "3.2.0"

dijets-sdk = { path = "../../sdk" }
debug-interface = { path = "../../common/debug-interface" }
dijets-logger = { path = "../../common/logger" }
dijets-config = { path = "../../config" }
dijets-workspace-hack = { path = "../../common/workspace-hack" }
dijets-framework-releases = { path = "../../language/dijets-framework/releases" }
dijets-genesis-tool = { path = "../../config/management/genesis" }
dijets-retrier = { path = "../../common/retrier" }
dijets-secure-storage = { path = "../../secure/storage" }
base64 = "0.13.0"
kube = "0.51.0"
k8s-openapi = { version = "0.11.0", default-features = false, features = ["v1_15"] }
