[package]
name = "executor"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets executor"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
fail = "0.4.0"
itertools = { version = "0.10.0", default-features = false }
once_cell = "1.7.2"
serde_json = "1.0.64"
serde = { version = "1.0.124", features = ["derive"] }

consensus-types = { path = "../../consensus/consensus-types"}
executor-types = { path = "../executor-types" }
bcs = "0.1.2"
dijets-crypto = { path = "../../crypto/crypto" }
dijets-logger = { path = "../../common/logger" }
dijets-metrics = { path = "../../common/metrics" }
dijets-infallible = { path = "../../common/infallible" }
dijets-secure-net = { path = "../../secure/net" }
dijets-state-view = { path = "../../storage/state-view" }
dijets-types = { path = "../../types" }
move-core-types = { path = "../../language/move-core/types" }
dijets-vm = { path = "../../language/dijets-vm" }
dijets-workspace-hack = { path = "../../common/workspace-hack" }
scratchpad = { path = "../../storage/scratchpad" }
storage-interface = { path = "../../storage/storage-interface" }

proptest = { version = "1.0.0", optional = true }

[dev-dependencies]
proptest = "1.0.0"
rand = "0.8.3"

dijets-framework-releases = { path = "../../language/dijets-framework/releases" }
compiler = { path = "../../language/compiler" }
executor-test-helpers = { path = "../executor-test-helpers" }
dijets-config = { path = "../../config" }
dijets-genesis-tool = {path = "../../config/management/genesis", features = ["testing"] }
dijets-temppath = { path = "../../common/temppath" }
dijetsdb = { path = "../../storage/dijetsdb" }
storage-interface = { path = "../../storage/storage-interface", features=["fuzzing"] }
dijets-transaction-builder = { path = "../../sdk/transaction-builder" }
vm-genesis = { path = "../../language/tools/vm-genesis" }

[features]
default = []
fuzzing = ["consensus-types/fuzzing", "dijets-crypto/fuzzing", "dijets-types/fuzzing", "proptest", "storage-interface/fuzzing"]
failpoints = ["fail/failpoints", "dijets-vm/failpoints"]
