[package]
name = "socket-bench-server"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets socket bench server"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
futures = "0.3.12"
tokio = { version = "1.8.1", features = ["full"] }
tokio-util = { version = "0.6.4", features = ["compat", "codec"] }

dijets-crypto = { path = "../../crypto/crypto" }
dijets-config = { path = "../../config" }
dijets-logger = { path = "../../common/logger" }
dijets-types = { path = "../../types" }
dijets-workspace-hack = { path = "../../common/workspace-hack" }
memsocket = { path = "../memsocket" }
netcore = { path = "../netcore", features = ["fuzzing", "testing"] }
network = { path = "../.", features = ["testing", "fuzzing"] }
network-builder = { path = "../builder"}
rand = "0.8.3"
