[package]
name = "dijets-transactional-test-harness"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Transactional testing framework for Move"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.6.1"
once_cell = "1.7.2"
anyhow = "1.0.38"
structopt = "0.3.21"
bcs = "0.1.2"

move-transactional-test-runner = { path = "../transactional-test-runner" }
language-e2e-tests = { path = "../e2e-tests" }
move-lang = { path = "../../move-lang" }
move-binary-format = { path = "../../move-binary-format" }
move-core-types = { path = "../../move-core/types" }
dijets-vm =  { path = "../../dijets-vm" }
dijets-types = { path = "../../../types", features = ["fuzzing"] }
dijets-crypto = { path = "../../../crypto/crypto" }
dijets-framework = { path = "../../dijets-framework" }
dijets-state-view = { path = "../../../storage/state-view" }
dijets-workspace-hack = { path = "../../../common/workspace-hack" }
move-command-line-common = { path = "../../move-command-line-common" }

[dev-dependencies]
datatest-stable = "0.1.1"

[[test]]
name = "tests"
harness = false
