[package]
name = "dijets-jellyfish-merkle"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets jellyfish merkle"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
byteorder = "1.4.3"
itertools = { version = "0.10.0", default-features = false }
mirai-annotations = "1.10.1"
num-derive = "0.3.3"
num-traits = "0.2.14"
once_cell = "1.7.2"
proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", optional = true }
rand = { version = "0.8.3", optional = true }
serde = { version = "1.0.124", features = ["derive"] }
thiserror = "1.0.24"

bcs = "0.1.2"
dijets-crypto = { path = "../../crypto/crypto" }
dijets-crypto-derive = { path = "../../crypto/crypto-derive" }
dijets-infallible = { path = "../../common/infallible" }
dijets-metrics = { path = "../../common/metrics" }
dijets-types = { path = "../../types" }
dijets-workspace-hack = { path = "../../common/workspace-hack" }

[dev-dependencies]
rand = "0.8.3"
proptest = "1.0.0"
proptest-derive = "0.3.0"

dijets-crypto = { path = "../../crypto/crypto", features = ["fuzzing"] }
dijets-types = { path = "../../types", features = ["fuzzing"] }

[features]
default = []
fuzzing = ["proptest", "rand", "proptest-derive", "dijets-crypto/fuzzing", "dijets-types/fuzzing"]
