[package]
name = "transaction-builder-generator"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets transaction-builder"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
heck = "0.3.2"
regex = "1.4.3"
structopt = "0.3.21"
textwrap = "0.13.4"
serde-reflection = "0.3.2"
serde-generate = "0.19.1"
serde_yaml = "0.8.17"

dijets-types = { path = "../../../types" }
dijets-workspace-hack = { path = "../../../common/workspace-hack" }
move-core-types = { path = "../../move-core/types" }
bcs = "0.1.2"

[dev-dependencies]
tempfile = "3.2.0"
which = "4.0.2"

[features]
default = []

[[bin]]
name = "generate-transaction-builders"
path = "src/generate.rs"
test = false
