[package]
name = "df-cli"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "CLI frontend for the Move compiler and VM (with Dijets Framework)"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
bcs = "0.1.2"
structopt = "0.3.21"

dijets-workspace-hack = { path = "../../../common/workspace-hack" }
move-core-types = { path = "../../move-core/types" }
move-cli = { path = "../../tools/move-cli" }
dijets-vm = { path = "../../dijets-vm" }
dijets-framework-releases = { path = "../../dijets-framework/releases" }

[dev-dependencies]
datatest-stable = "0.1.1"

[[bin]]
name = "df-cli"
path = "src/main.rs"

[[test]]
name = "cli_testsuite"
harness = false
