[package]
name = "many-keys-stress-test"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets channel"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
futures = "0.3.12"
channel = { path = "../" }
dijets-workspace-hack = { path = "../../workspace-hack" }
structopt = "0.3.21"
