[package]
name = "dijets-log-derive"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[lib]
proc-macro = true

[dependencies]
dijets-workspace-hack = { path = "../../workspace-hack" }
syn = { version = "1.0.64", features = ["extra-traits"] }
quote = "1.0.9"
proc-macro2 = "1.0.24"
