[package]
name = "safety-rules"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
once_cell = "1.7.2"
rand = { version = "0.8.3", default-features = false }
proptest = { version = "1.0.0", optional = true }
rand_core = "0.6.2"

crash-handler = { path = "../../common/crash-handler" }
consensus-types = { path = "../consensus-types" }
bcs = "0.1.2"
dijets-config = { path = "../../config" }
dijets-crypto = { path = "../../crypto/crypto" }
dijets-global-constants = { path = "../../config/global-constants"}
dijets-infallible = { path = "../../common/infallible" }
dijets-logger = { path = "../../common/logger" }
dijets-proptest-helpers = { path = "../../common/proptest-helpers", optional = true }
dijets-secure-net = { path = "../../secure/net" }
dijets-secure-push-metrics = { path = "../../secure/push-metrics" }
dijets-secure-storage = { path = "../../secure/storage" }
dijets-temppath = { path = "../../common/temppath" }
dijets-types = { path = "../../types" }
dijets-vault-client = { path = "../../secure/storage/vault" }
dijets-workspace-hack = { path = "../../common/workspace-hack" }
serde = { version = "1.0.124", default-features = false }
thiserror = "1.0.24"

[dev-dependencies]
criterion = "0.3.4"
tempfile = "3.2.0"
proptest = "1.0.0"

consensus-types = { path = "../consensus-types", features = ["fuzzing"] }
dijets-config = { path = "../../config", features = ["fuzzing"] }
dijets-proptest-helpers = { path = "../../common/proptest-helpers" }
dijets-secure-storage = { path = "../../secure/storage", features = ["testing"] }

[[bench]]
name = "safety_rules"
harness = false
required-features = ["testing"]

[[test]]
name = "binary"
required-features = ["testing"]

[features]
default = []
fuzzing = ["consensus-types/fuzzing", "dijets-config/fuzzing", "proptest", "dijets-proptest-helpers"]
testing = ["dijets-secure-storage/testing"]
