[package]
name = "language-e2e-testsuite"
version = "0.1.0"
edition = "2018"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets language e2e tests"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false

[dependencies]
serde_json = "1.0.64"
language-e2e-tests = { path = "../testing-infra/e2e-tests" }
bytecode-verifier = { path = "../bytecode-verifier" }
bcs = "0.1.2"
compiler = { path = "../compiler" }
dijets-keygen = { path = "../dijets-tools/dijets-keygen" }
dijets-crypto = { path = "../../crypto/crypto", features = ["fuzzing"] }
dijets-types = { path = "../../types", features = ["fuzzing"] }
move-core-types = { path = "../move-core/types" }
move-vm-runtime = { path = "../move-vm/runtime" }
move-vm-types = { path = "../move-vm/types" }
dijets-transaction-builder = { path = "../../sdk/transaction-builder"}
move-binary-format = { path = "../move-binary-format" }
dijets-vm = { path = "../dijets-vm" }
proptest = "1.0.0"
dijets-logger = { path = "../../common/logger" }
dijets-framework-releases = { path = "../dijets-framework/releases" }
dijets-workspace-hack = { path = "../../common/workspace-hack" }
dijets-writeset-generator = { path = "../dijets-tools/writeset-transaction-generator"}
dijets-state-view = { path = "../../storage/state-view" }

[features]
default = ["dijets-transaction-builder/fuzzing"]
