[package]
name = "dijets-framework-releases"
version = "0.1.0"
edition = "2018"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets Framework Releases"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false


[dependencies]
move-command-line-common = { path = "../../move-command-line-common" }
dijets-crypto = { path = "../../../crypto/crypto" }
dijets-types = { path = "../../../types" }
dijets-workspace-hack = { path = "../../../common/workspace-hack" }
move-binary-format = { path = "../../move-binary-format" }

anyhow = "1.0.38"
include_dir = "0.6.0"
bcs = "0.1.2"
once_cell = "1.7.2"

[dev-dependencies]
bytecode-verifier = { path = "../../bytecode-verifier" }
