[package]
name = "dijets-vault-client"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
repository = "https://github.com/dijets/dijets"
description = "Dijets's Restful Vault Client"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
base64 = "0.13.0"
chrono = "0.4.19"
once_cell = "1.7.2"
proptest = { version = "1.0.0", optional = true }
native-tls = "0.2.7"
serde = { version = "1.0.124", features = ["derive"], default-features = false }
serde_json = "1.0.64"
thiserror = "1.0.24"
ureq = { version = "1.5.4", features = ["json", "native-tls"], default-features = false }

dijets-crypto = { path = "../../../crypto/crypto" }
dijets-proptest-helpers = { path = "../../../common/proptest-helpers", optional = true }
dijets-types = { path = "../../../types", optional = true }
dijets-workspace-hack = { path = "../../../common/workspace-hack" }

[dev-dependencies]
proptest = "1.0.0"

dijets-proptest-helpers = { path = "../../../common/proptest-helpers" }
dijets-types = { path = "../../../types", features = ["fuzzing"] }

[features]
fuzzing = ["proptest", "dijets-proptest-helpers", "dijets-types"]
