[package]
name = "jsonrpc-types-proto"
version = "0.0.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets JSONRPC Proto Types"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
prost = "0.8.0"
serde = { version = "1.0.124", default-features = false }
serde_json = "1.0.64"

dijets-crypto = { path = "../../../crypto/crypto" }
dijets-types = { path = "../../../types" }
dijets-json-rpc-types = { path = ".." }
dijets-workspace-hack = { path = "../../../common/workspace-hack" }

[build-dependencies]
prost-build = "0.8.0"
