[package]
name = "genesis-viewer"
version = "0.1.0"
authors = ["Dijets Association <opensource@dijets.com>"]
description = "Dijets genesis viewer"
repository = "https://github.com/dijets/dijets"
homepage = "https://dijets.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bcs = "0.1.2"
dijets-types = { path = "../../../types" }
dijets-workspace-hack = { path = "../../../common/workspace-hack" }
move-binary-format = { path = "../../move-binary-format" }
move-core-types = { path = "../../move-core/types" }
dijets-resource-viewer = { path = "../dijets-resource-viewer"}
vm-genesis = { path = "../vm-genesis" }
dijets-framework-releases = { path = "../../dijets-framework/releases" }
move-vm-test-utils = { path = "../../move-vm/test-utils" }

structopt = "0.3.21"
